name: Continues Integration

on:
  workflow_dispatch: null
  push:
  pull_request:

jobs:
  run-tests-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9','3.10','3.11', '3.12', '3.13' ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup python 3
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: install the package with dev tools
        run: make dev-install

      - name: run unit tests
        run: make unit-test

      - name: run linter
        run: make lint
