name: Unit Tests

on:
  workflow_dispatch: null
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9','3.10','3.11', '3.12' ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup python 3
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: install or update Python build system
        run: python3 -m pip install -U wheel setuptools certifi pip

      - name: install the package with dev tools
        run: make dev-install

      - name: run unit tests
        run: make unit-test

